### ISSUE TITLE
No PreparedStatements = MySQL Injections

### ISSUE THREAD

**Issue by CodeBeasty** [ShepherdJerred/stAnalytics#1]
Hey, So I noticed you are using ResultSets but no PreparedStatements? That is really unsecure and you should use MySQL Pooling like HikariCP or BoneCP.

**Comment by ShepherdJerred** [comment]
It's "on my list", however as far as I know, since this is ran on the server without any player input, and all the queries are hard coded, it wouldn't be possible to have an injection attack (except maybe by a username, or somehow a UUID).

MySQL pooling is also something to be added in the future, however performance is good as it is, the plugin runs all queries async (Except the join event isn't async and I need to change that). I'd rather focus on other plugins at the moment.

**Comment by ShepherdJerred** [comment]
All MySQL is now done with prepared statements and using HikariCP
